#!/usr/bin/make

export BASH=bash
DOCKER_DIR=../docker
APP_FOLDER_NAME=

ifeq ($(APP_FOLDER_NAME), )
$(error `APP_FOLDER_NAME` can not be null)
endif

copy-env:
	cp /var/www/docker/.env.example /var/www/$(APP_FOLDER_NAME)/.docker
up:
	cd $(DOCKER_DIR) && exec docker-compose --env-file ../$(APP_FOLDER_NAME)/.docker up -d nginx
down:
	cd $(DOCKER_DIR) && exec docker-compose down
cli:
	cd $(DOCKER_DIR) && exec docker-compose exec --user=laradock workspace zsh
